mymvc_core/Controllers/AdminLTEController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mymvc_core.Models;
using mymvc_core.Services;
using Microsoft.EntityFrameworkCore;
using mymvc_core.Services.Exceptions;
using mymvc_core.Services.interfaces;
using Microsoft.AspNetCore.Authorization;

namespace mymvc_core.Controllers
{  
    public class AdminLTEController : Controller
    {


        private readonly IMessageServer _messageServer;

        public AdminLTEController(IMessageServer messageServer)
        {

            _messageServer = messageServer;
        }

        /// <summary>
        /// 消息视图
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Messages()
        {

            return View(await _messageServer.GetAllMessageAsync());

        }

        /// <summary>
        /// 添加消息的视图
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Add(int? id)
        {
            try
            {
                if (id != null)
                {
                    TempData["edit"] = 1;
                    return View(_messageServer.GetMessagesById(id.GetValueOrDefault()));
                }
            }
            catch (NotFoundException e)  
            {
                TempData["ErrorMessage"] = e.Message;
                return StatusCode(404);          

            }
            return View();

        }

        /// <summary>
        /// 添加消息的表单提交action
        /// </summary>
        /// <param name="messages"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Messages messages)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await _messageServer.Add(messages);
                    return RedirectToAction(nameof(Messages));

                }
                catch (ModelValidationException e)
                {
                    ModelState.AddModelError("模型有错误", e.Message);
                    return View(messages);
                }
                catch (DbUpdateException e)
                {
                    TempData["ErrorMessage"] = e.Message;
                    return StatusCode(500);
                }
            }
            else
            {
                return View(messages);
            }
        }

        /// <summary>
        /// 编辑消息
        /// </summary>
        /// <param name="messages"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Messages messages)
        {
            if (messages?.Id == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await _messageServer.UpdateOne(messages);
                    return RedirectToAction(nameof(Messages));

                }
                catch (ModelValidationException e)
                {

                    ModelState.AddModelError("模型有错误", e.Message);
                    return View(messages);
                }
                catch (DbUpdateException e)
                {
                    TempData["ErrorMessage"] = e.Message;
                    return StatusCode(500, e.Message);
                }
            }
            else
            {
                return View(messages);
            }
        }

        /// <summary>
        /// 删除消息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _messageServer.DelectOne(id);
                return RedirectToAction(nameof(Messages));
            }
            catch (DbUpdateException e)                  
            {
                TempData["ErrorMessage"] = e.Message;
                return StatusCode(400);
            }
        }
    }
}

mymvc_core/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace mymvc_core.Controllers
{
    public class ChatController : Controller
    {
        /// <summary>
        /// 聊天室。
        /// </summary>
        /// <returns></returns>
        public IActionResult ChatRoom()
        {
            
            return View();
        }

        /// <summary>
        /// 拼图游戏
        /// </summary>
        /// <returns></returns>
        public IActionResult Jigsaw()
        {

            List<int> c = new List<int> { 1,2,3,4,5,6,7,8};
            c.ListRandom();
           
            if (!c.ListCheck())
            {
                c.ListChange();
            }
            ViewBag.c = c;

            return View();
        }
    }
}

mymvc_core/Views/Shared/_ControlSidebar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<aside class="control-sidebar control-sidebar-dark">
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">快速导航</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="@Url.Action("main", "Home")">
                        <i class="menu-icon fa fa-university bg-blue"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">大标题</h4>
                            <p>内容描述</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("New", "Movements")">
                        <i class="menu-icon fa fa-file bg-purple"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">大标题</h4>
                            <p>内容描述</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("New", "Transfers")">
                        <i class="menu-icon fa fa-exchange bg-yellow"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">大标题</h4>
                            <p>内容描述</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("New", "Projects")">
                        <i class="menu-icon fa fa-thumb-tack bg-gray"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">大标题</h4>
                            <p>内容描述</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("LogOut", "Identity")">
                        <i class="menu-icon fa fa-credit-card bg-green"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">登出</h4>
                            @if (SignInManager.IsSignedIn(User))
                            {
                        <p>
                            @User.Identity.Name
                        </p>
                            }
                            else
                            {
                                <p>
                                    未登录
                                </p>
                            }

                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</aside>

<div class="control-sidebar-bg"></div>

mymvc_core/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.2
    </div>
    <strong>Copyright &copy; @DateTime.Today.Year <a href="http://taozixiongtai.top/">taozixiongtai</a></strong>
</footer>

mymvc_core/Views/Shared/_Header.cshtml
<header class="main-header">
    <a href="@Url.Action("Index","home")" class="logo">
        <span class="logo-mini"><b>sample</b></span>
        <span class="logo-lg">sample</span>
    </a>

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">收缩</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

mymvc_core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -taozixiongtai</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <environment include="Development">

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    </environment>

    <script src="~/js/site.min.js"></script>
    <script src="~/js/init.js"></script>
</head>




<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
       
        <partial name="_Header" />
        <partial name="_Sidebar" />
        @RenderBody()                                   
        <partial name="_ControlSidebar" />
        <partial name="_Footer" />
                                 
    </div>

  
</body>
</html>

mymvc_core/Views/Shared/_Sidebar.cshtml
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">菜单</li>


            <li>
                <a href="@Url.Action("Index", "home")"><i class="fa fa-tachometer"></i> <span>主页</span></a>
            </li>






            <li class="treeview">
                <a href="@Url.Action("Messages","AdminLTE")">
                    <i class="fa fa-cogs"></i> <span>AdminLTE</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Messages", "AdminLTE")"><i class="fa fa-circle-o"></i>查看留言</a></li>
                    <li><a href="@Url.Action("Add", "AdminLTE")"><i class="fa fa-circle-o"></i>添加留言</a></li>
                </ul>
            </li>


            <li class="treeview">
                <a href="#">
                    <i class="fa fa-thumb-tack"></i> <span>用户管理</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("ConfirmEmail", "identity")"><i class="fa fa-circle-o"></i>添加邮箱</a></li>
                    <li><a href="@Url.Action("ChangePassword", "identity")"><i class="fa fa-circle-o"></i>修改密码</a></li>
                    <li><a href="@Url.Action("AddUser", "UserManager")"><i class="fa fa-circle-o"></i>权限操作</a></li>
                </ul>
            </li>


            <li class="treeview">
                <a href="#">
                    <i class="fa fa-thumb-tack"></i> <span>Signalr</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("ChatRoom", "Chat")"><i class="fa fa-circle-o"></i>聊天室</a></li>
                    <li><a href="@Url.Action("Jigsaw", "Chat")"><i class="fa fa-circle-o"></i>拼图</a></li>
                </ul>
            </li>

        </ul>
    </section>
</aside>